databases:
  - name: shopyatte
    plan: free
    databaseName: yattedb
    user: yattedb_user

services:
  - type: web
    plan: free
    name: back
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn back.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: "postgres://yattedb_user:jAn1Kn6Y7BZJHw5Ql684KA1RaTHkcJjD@dpg-cnkfjgun7f5s73drt26g-a.frankfurt-postgres.render.com/yattedb"
        fromDatabase:
          name: yattedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4