# Generated by Django 5.0.2 on 2024-02-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='texte',
            field=models.TextField(blank=True),
        ),
    ]
