# Generated by Django 5.0.2 on 2024-02-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_produit_texte'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='pribarrer',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
