# Generated by Django 5.0.2 on 2024-02-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_produit_pribarrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
